language: perl6
before_install:
  - sudo add-apt-repository ppa:xapian-core/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libxapian-dev
install:
  - rakudobrew build-panda
before_script:
  - panda installdeps .
  - panda-build
script:
  - panda-test
